### ISSUE TITLE
async_forward_entry_setup will be deprecated in Home Assistant 2025.6

### ISSUE THREAD

**Issue by ErikvO** [txxa/hass-duplicati#14]
## System Information

version | core-2024.10.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4996
Installed Version | 2.0.1
Stage | running
Available Repositories | 1431
Downloaded Repositories | 20

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.09.1
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 219.4 GB
disk_used | 37.8 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | deCONZ (7.0.0), Studio Code Server (5.16.3), RPC Shutdown (2.5), Samba share (12.3.2), MariaDB (2.7.1), phpMyAdmin (0.10.0), Z-Wave JS (0.7.2), ESPHome (2024.9.2), AdGuard Home (5.1.4), Advanced SSH & Web Terminal (19.0.0), CUPS (1.0), chrony (4.0.1), Mosquitto broker (6.4.1), Frigate (0.14.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 11
views | 25
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 24, 2024 at 11:13 AM
-- | --
current_recorder_run | October 3, 2024 at 9:59 AM
estimated_db_size | 1391.11 MiB
database_engine | mysql
database_version | 10.11.6

</details>

### Checklist

- [ ] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/txxa/hass-duplicati/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Found in the logs after upgrading to Home Assistant Core 2024.10.0

Detected that custom integration 'duplicati' calls async_forward_entry_setup for integration, duplicati with title: Backup Backup (host=10.1.1.2:8200, id=1) and entry_id: 01J6VKSE8Z05859DBK21B2Q4WM, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/duplicati/__init__.py, line 99: hass.async_create_task(, please create a bug report at https://github.com/txxa/hass-duplicati/issues

### Reproduction steps

1. Upgrade to Home Assistant Core 2024.10.0
2. Find warnings in the logs.

**Comment by txxa** [comment]
Hi @ErikvO 

Thanks for the bringing this up.
It will be fixed with the next release.
