### ISSUE TITLE
binary_sensor instead of sensor.xxxx_status

### ISSUE THREAD

**Issue by bastgau** [txxa/hass-duplicati#17]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/txxa/hass-duplicati/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Hello.

Thanks for your work. I have just installed the new beta version.

Currently the `backup status` is store in a `sensor` with the value "OK".

### Describe the solution you'd like

 It could be stored in a binary_sensor with a `device_class` : `problem`.

With a binary_sensor, we could use the feature related to a binary_sensor (color, etc)

### Describe alternatives you've considered

Thanks.

### Additional context

...

**Comment by txxa** [comment]
Hi @bastgau 

I will as well have a look into it.

**Comment by bastgau** [comment]
Feature seems to be OK in the last beta version ([v0.2.0_beta2](https://github.com/txxa/hass-duplicati/releases/tag/v0.2.0_beta2)) ! Thanks.
