### ISSUE TITLE
New sensor containing next backup date

### ISSUE THREAD

**Issue by bastgau** [txxa/hass-duplicati#19]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/txxa/hass-duplicati/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Currently we are not able to retrieve the next backup date.

### Describe the solution you'd like

It should be interesting if we could retrieve this information in Home Assistant.

### Describe alternatives you've considered

Creating a new sensor containing the date of the next planned backup named : "sensor.**_next_date"

### Additional context

Don't know if my request is possible. Thanks for your work.

**Comment by txxa** [comment]
Hi @bastgau,

I had a look into this and I won't add a new sensor, as I don't use Duplicati as scheduler for my backups and I don't want to have sensors that are not used or are inactive.

However, I will adapt the integration to extract the next scheduled backup date (if available) and add it as state attribute to the last_backup_execution sensor.

The next beta will contain this enhancement (besides a few others).

**Comment by bastgau** [comment]
The information as attribute is fine too. 😉

Thanks.

**Comment by txxa** [comment]
Feel free to test it ☺️ 
https://github.com/txxa/hass-duplicati/releases/tag/v0.2.0_beta2

**Comment by bastgau** [comment]
Juste updated. Everything seems to be OK for me !
