### ISSUE TITLE
Backup ID

### ISSUE THREAD

**Issue by bastgau** [txxa/hass-duplicati#7]
### System Health details

During the configuration the backup ID information is requested.

Where can we find this information ?

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/txxa/hass-duplicati/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

N/A

### Reproduction steps

N/A

### Debug logs

```text
N/A
```

**Comment by txxa** [comment]
Hi @bastgau 

This actually is a good point, thanks for bringing it up.
I will adapt/extend the configuration flow to allow selecting from a list of existing backups.

In meanwhile you can get the backup ID from the URL if you edit the backup job in Duplicati (Configuration section -> Edit)

URL example of backup in edit mode:
`https://duplicati.local:8200/ngax/index.html#/edit/1`
In this example the backup ID is 1

**Comment by bastgau** [comment]
Hi @txxa

Unfortunately, the same message always appears : "Invalid backup ID"

Do you support when a password is set on Duplicati ?

**Comment by txxa** [comment]
Hi @bastgau

No, the password protection mode is currently not supported.
I will have a look into this option and add support for it if not too much effort is needed.

**Comment by bastgau** [comment]
When I dsactivate the password, the same error appears ... Don't know why.

```
API response error: Set-Cookie header not found in response
API response error: nipogi.local:8300
API response error: nipogi.local
```

**Comment by txxa** [comment]
What Duplicati version are you using?

**Comment by bastgau** [comment]
This version `Duplicati - 2.0.8.1_beta_2024-05-07`.

**Comment by txxa** [comment]
Hi @bastgau 

I will soon release v0.2.0 which adds:
- dynamic backup management (select available backups from a list)
- support for password protection mode (tested with Duplicati 2.0.8.1_beta_2024-05-07)
- other improvements and bugfixes

**Comment by bastgau** [comment]
Great news ! Thanks.

**Comment by bastgau** [comment]
Beta works well without password.
I have still an issue when a password is configured.

**Comment by txxa** [comment]
The password mode is not yet available in the beta you tried, only the backup selection.

**Comment by txxa** [comment]
I just created a new beta version containing as well the password mode support.
Please try this one and let me know if it is working for you.

**Comment by bastgau** [comment]
Everything seems to be work well !

Thanks.
